gems:
  - jekyll-redirect-from

name: дорога хороша

excerpt_separator: <!--lurk-->

permalink: /:year/:month/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
