gems:
  - jekyll-redirect-from

name: дорога хороша
url: https://scary.tasty.sexy
author:
  name: Сёма Мрачный
  email: scary@tasty.sexy

excerpt_separator: <!--lurk-->

permalink: /:year/:month/:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
