gems:
  - jekyll-redirect-from

name: дорога хороша
url: https://sad.st
author:
  name: Сёма Мрачный
  email: scarylittlerabbit@gmail.com

excerpt_separator: <!--lurk-->

permalink: /:year/:month/:title/

collections:
  rtags:
    output: true
    permalink: /tag/:name/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  -
    scope:
      path: ""
      type: "rtags"
    values:
      layout: "tags"
